version: '3'
services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@2019
      - TZ=Asia/Shanghai
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /data/mysql/sql/:/opt/
    command: mysqld --sql-mode='' --user=root
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1024M
    networks:
      - custom_net

networks:
  custom_net:
    external:
      name: app_net