version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address ":9001"
    volumes:
      - /data/minio/data:/data
      - /data/minio:/minio
      - /data/minio/config:/root/.minio
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234 #大于等于8位
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
    networks:
      - custom_net
networks:
  custom_net:
    external:
      name: app_net